apiVersion: v1
kind: Service
metadata:
  labels:
    app: dogapp
  name: dogapp
spec:
  type: "LoadBalancer"
  ports:
  - name: "dogapp"
    port: {{ .Values.app.port }} # external port
    targetPort: 5000 # Pod
  selector:
    app: dogapp
